<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\WikiCopilotAssistant.Application\WikiCopilotAssistant.Application.csproj" />
    <ProjectReference Include="..\WikiCopilotAssistant.Infrastructure\WikiCopilotAssistant.Infrastructure.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
</Project>
